### ISSUE TITLE
Оставьте либо просто умножение, либо разделите тысячи '_'

### ISSUE THREAD

**Issue by coursar** [Daaamir2/DepositCalculator#1]
https://github.com/Daaamir2/DepositCalculator/blob/4b42af14c998cbcd8d509076fc064210c9c1fb1f/src/main/java/ru/itpark/DepositCalculator.java#L12

**Comment by Daaamir2** [comment]
Исправлено

**Comment by coursar** [comment]
@Daaamir2, пока вижу в репозитории только один коммит.

**Comment by Daaamir2** [comment]
А сейчас?
